### ISSUE TITLE
Первая часть

### ISSUE THREAD

**Issue by Valentine-doc** [Valentine-doc/GITHomeworkTHREEForEG#2]
1. Клонировать репозиторий, создать отдельную ветку и переключиться на неё.
2. Нужно заменить в проекте:
в классе Animal заменить ReactToCar на ReactToPeople, текст для вывода в консоль заменить на: реагирует на человека
в классе Dog заменить ReactToCar на ReactToPeople, текст для вывода в консоль заменить на: радостно скулит.
в классе Program удалить строки 18-28
добавить в класс Program строку: Animal myAnimal = new() (или любую другую вариацию этой строки).

**Comment by VValentinesDay** [comment]
С гордостью докладываю о выполнении поставленной задачи, без проишествий

**Comment by Valentine-doc** [comment]
its ok
